#!/bin/bash

# Add this crontab entry to the root user on each satellite box that will receive all keys:
#
# 0,15,30,45 * * * * /root/sync_ssh_keys/check_update

HAM=no

#################################################################################################

if scp root@jump-debian.wdatkinson.com:~/sync_ssh_keys/update ./ >&/dev/null; then 
        if [ "$HAM" = "yes" ]; then
                scp root@jump-debian.wdatkinson.com:~/.ssh/authorized_keys ~/.ssh/authorized_keys_per;
		scp root@jump-debian.wdatkinson.com:~/.ssh/authorized_keys_ham ~/.ssh/authorized_keys_ham; 
        	cat ~/.ssh/authorized_keys_per > ~/.ssh/authorized_keys
		cat ~/.ssh/authorized_keys_ham >> ~/.ssh/authorized_keys
	else 
                scp root@jump-debian.wdatkinson.com:~/.ssh/authorized_keys ~/.ssh/authorized_keys;
        fi
fi
